version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 4856
      MYSQL_DATABASE: payhere
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      DB_URL: mysql://root:4856@db:3306/payhere